<?php

namespace Webfactor\WfBasicFunctionPackage\Http\Controllers\view;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Webfactor\WfBasicFunctionPackage\Models\Media;

class MediaController extends \Webfactor\WfBasicFunctionPackage\Http\Controllers\api\MediaController
{
    public function index($key)
    {
        return redirect(parent::index($key)); // TODO: Change the autogenerated stub
    }
}
