<?php

namespace Webfactor\WfBasicFunctionPackage\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Media extends Model
{
    use HasFactory;


    public function header_image()
    {
        return $this->belongsTo(Gallery::class);
    }

    protected static function booting()
    {
        parent::booting(); // TODO: Change the autogenerated stub

        static::saved(function($test) {
            info($test);
        });
    }

    public static function boot()
    {
        /**
         * TODO:
         *  -remove doesn't work
         */
        parent::boot();

        static::saved(function($callback) {
            info($callback);
            $gallery = Gallery::find($callback->model_id);
//            info($gallery);
//            sleep(5);
//            info($gallery->getFirstMedia("header")?->id);
            if($gallery->header_image_id != $callback->id)
            {
                $gallery->header_image_id = $callback->id;
                $gallery->save();
            }
            info($gallery);
//            info($gallery->header_image_id);

            info("why");
        });
    }
}
